# This is a sample config file for the python scripts
# You can copy this file and rename it to config.yml
# The config file is broken up into sections, each section is a script except the global section
# The rest of the options are script specific
global:
  run_now: true # If true it will run the script immediately, if false it will wait until the schedule_hour
  schedule_hour: 4 # This is the hour of the day you want the script to run, it's based on a 24 hour clock and defaults to 4am. Set to -1 to disable scheduling and quit after running.
  log_level: info # log_level can be: debug, info, warning, error, critical
  radarr:
    # name is the name of the radarr instance, this is used to reference the instance in other scripts
    - name: radarr_1
      # api is the api key for the radarr instance
      api: abcdefghijlmnop
      # url is the url for the radarr instance
      url: http://localhost:7878
    - name: radarr_2
      api: abcdefghijklmnop
      url: http://localhost:1212
  sonarr:
    # name is the name of the sonarr instance, this is used to reference the instance in other scripts
    - name: sonarr_1
      # api is the api key for the sonarr instance
      api: abcdefghijlmnop
      # url is the url for the sonarr instance
      url: http://localhost:8989
    # name is the name of the second sonarr instance, this is used to reference the instance in other scripts, names must match
    - name: sonarr_2
      api: abcdefghijlmnop
      url: http://localhost:9090
  plex:
    # name is the name of the plex instance, this is used to reference the instance in other scripts
    - name: plex
      # api is the token key for the plex instance, if you don't know your token please see https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
      api: abcdefghijlmnop
      # url is the url for the plex instance
      url: http://localhost:32400

# THIS SCRIPT SYNCS GDRIVE TO A LOCAL FOLDER. ANYTHING UNIQUE IN THE FOLDER WILL BE DELETED.
# -> You can use client_id, client_secret, and token to authenticate, or you can use gdrive_sa_location to use a service account.
# DRAZZILB GDRIVE ID: 1VeeQ_frBFpp6AZLimaJSSr0Qsrl6Tb7z
# This script is meant to be used in conjuction with Plex-Meta-Manager, however it can be used on it's own.
# This is a script base of this one: https://discord.com/channels/492590071455940612/1124032073557086258/1126226814629576858
sync_gdrive:
  run: true # If false, it will skip this step
  client_id: asdasds.apps.googleusercontent.com # Client ID for rclone usually ends with .apps.googleusercontent.com
  client_secret: GOCSPX-asda123 # Client Secret for rclone, usually starts with GOCSPX-
  token: # The token for rclone, this is the output of rclone config dump that needs to run manually
  # Token looks like this: { "access_token": "value", "token_type": "Bearer", "refresh_token": "value", "expiry": "value" }
  gdrive_sa_location: /config/rclone_sa.json # The location of your rclone service account file (JSON)
  gdrive_sync: # example of multiple gdrive_id's with multiple sync_locations as objects, we have deprecated gdrive_id and sync_location so please use this instead
    - id: 1VeeQ_frBFpp6AZLimaJSSr0Qsrl6Tb7z # The ID of the folder you want to sync from
      location: /data/input # Where you want to sync the posters to
    - id: 1wrSru-46iIN1iqCl2Cjhj5ofdazPgbsz # The ID of the folder you want to sync from
      location: /data/input2 # Where you want to sync the posters to

# The renamer script is used to rename your posters to match your Plex Collections and Media Folder names for Movies and TV Shows
# This script is meant to be used in conjuction with Plex-Meta-Manager, however it can be used on it's own.
# This is a script base of this one: https://github.com/Drazzilb08/userScripts
renamer:
  run: true # If false, it will skip this step
  # Options are 'true' or 'false'
  dry_run: true # dry_run can be true or false, if true it will not actually rename anything
  asset_folders: false
  # Options are 'copy' or 'move'
  action_type: copy
  print_only_renames: false # If print_only_renames is True, then we don't want to print files that don't need to be renamed
  # Library names are used to match collections posters to the collections listed w/in Plex. Typically Movie Libraries are used
  library_names:
    - Movies
    - TV Shows
    - Anime Movies
  # Where your ingest movies folder is (THe source and destination should not be the same directory)
  # The order of the source dirs matters
  # Can be a single dir or a list of dirs
  source_dirs: /path/to/posters/ <--- Lowest priority
  # What posters you'd like to override the source dirs with.
  # This dir will take priority for assets over source_dirs
  # To not use any override, simply leave it blank or remove it from the config
  # Can be a single dir or a list of dirs
  source_overrides:
    - /path/to/posters/override/ <--- Middle priority
    - /path/to/posters/override2/ <--- Highest priority
  # Where your posters are going to go. In my usecase I use Plex-Meta-Manager. This is the /config/assets dir for PMM for me.
  destination_dir: /path/to/poster/destination
  # The thresholds are used to consider what is a "Match", As with any automation there is never a 100% guarantee of accuracy. There will be times the script will mess up.
  # If however you see it messing up more often on things you can restrict the threshold.
  # 0 = Anything goes, 100 = Must be exact match
  # The default numbers here are based upon what I've seen to be the most effective, I've had one-offs where I had to manually fix things.
  # Eg. Hanna vs Anna, One letter difference and in the case I had the years were the same too.
  movies_threshold: 96
  series_threshold: 96
  collection_threshold: 99
  # Decide which radarr instance you will be using for renamer, this is useful if you have for example: A Sonarr/Sonarr-Anime and/or Radarr/Radarr-Anime
  # If you however duplicate entries between a Radarr/Radarr4K for example. this won't help and will only double the work for the script for no gain.
  radarr:
    - name: radarr_1
  sonarr:
    - name: sonarr_1
    - name: sonarr_2

# The fix_border script is used to fix the border colour of posters that sync_gdrive script downloads.
# This script is meant to be used in conjuction with Plex-Meta-Manager, however it can be used on it's own.
# This is a script base of this one: https://github.com/listentofaze/mm2k-border-replacer/tree/main#mm2k-poster-border-colour-replacer
fix_border:
  run: true # If false, it will skip this step
  input_folder: /data/input # Where your posters are going to be coming from
  output_folder: /data/fix_posters # Where your posters are going to go
  border_color: none # This will remove the border of the image, but you can also add a color to change th border to any hex color, Ej: '#000000'
  overwrite_existing: true # If true it will overwrite the existing poster, if false it will skip the poster
  resize: false # If true it will resize the poster to 1000x1500, this requires border_color to be set to a 'none'
  bottom_only: false # If true it will only keep the bottom border, this requires border_color to be set to a color Ej: '#000000'

# This is a script that will take your existing collections, Movies, and Series, and match them to your Plex Library and/or your Media Dir
unmatched_assets:
  run: true # If false, it will skip this step
  # Optional: Add libraries you want the script to check for unmatched assets
  asset_folders: false
  library_names:
    - Movies
    - Anime Movies
  # Optional: Add collections you'd like to ignore
  # These defaults are based upon my own usecase, you can remove them or add your own
  ignore_collections:
    - "Star Wars Universe"
    - "DC Animated Universe"
    - "Alien / Predator"
    - "Rocky / Creed"
    - "MonsterVerse"
    - "Star Trek"
    - "X-Men Universe"
    - "In Association With Marvel"
    - "View Askewniverse"
    - "The Mummy Universe"
    - "Middle Earth"
    - "In Association With DC"
    - "Wizarding World"
    - "Fast & Furious"
    - "The Spiderverse"
    - "Marvel Cinematic Universe"
    - "The Conjuring Universe"
    - "The Batman Universe"
    - "Collectionless"
    - "DC Extended Universe"
  assets_path: /path/to/poster-assets/
  media_paths:
    - /path/to/media/folders/movies
    - /path/to/media/folders/tv-shows
